# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-28 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
