# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-01 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200331_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 8, 2, 9, 4, 676510, tzinfo=utc), null=True),
        ),
    ]
