# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-31 23:15
from __future__ import unicode_literals

import bids.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[bids.models.empty_bid]),
        ),
    ]
